### ISSUE TITLE
Store the usage parameters program

### ISSUE THREAD

**Issue by Max2433BO** [DarwinNE/FidoCadJ#126]
Hi, @DarwinNE 

I send a request from a Electroyou forum user:

> Is it possible that fidocadj remember the parameters with which it was closed?

Specifically: location and size (expanded or reduced) of the window, setting zoom, grid, grid block, ...

Bye, Max

**Comment by DarwinNE** [comment]
Sounds reasonable!

**Comment by DarwinNE** [comment]
FidoCadJ now saves:
- the size and the position of the window
- the visibility of the Library tree (see #127)
- the snap to grid state
- the visibility of the grid

I do not think that the current zoom must be saved too, since every time a new file is opened the zoom is recalculated and if one starts a new drawing it is better to start with a reasonable zoom setting (400%).
