### ISSUE TITLE
Inconsistent paths

### ISSUE THREAD

**Issue by Stemby** [DarwinNE/FidoCadJ#55]
I think `src/net/sourceforge/*` should be replaced by shorter and/or more logical paths.

**Comment by DarwinNE** [comment]
Hi,
if you mean those paths in the source code, this has to do with the package structure in Java.
It would be possible to change that now, but the price to pay would be to modify practically *all* the source files, which is a very unpleasant and unrewarding work.
Years ago we went from a more simple package organization towards this choice, which followed the common Java convention, since we had an homepage here http://fidocadj.sourceforge.net
Since that it is a matter of an internal representation, I think it is better to keep it as it is for the moment.
