### ISSUE TITLE
Compatibility mode with FidoCAD

### ISSUE THREAD

**Issue by wall87** [DarwinNE/FidoCadJ#75]
Hi
When I'm going to draw the curve button is freezes and not selectable, even once draw a line will not let me choose if I want an arrow.

**Comment by DarwinNE** [comment]
Hi @wall87,
  this is normal, since the original "FidoCAD per Windows" (not developed since 2001) did not let to do such kind of things. The "compatibility mode" is meant for those who want to obtain a drawing compatible with that very old program.

However, there is a usability issue, which in the past caused a lot of troubles for users: people activate that mode and then forget about it wandering after a wile why certain functions are not available.

For that reason, from version 0.24.6 (we are working on that right now), the "FidoCAD compatibility mode" will not be conserved each time FidoCadJ is restarted.

Kind regards,
D.

**Comment by DarwinNE** [comment]
Here is a screenshot of FidoCadJ running with the 'FidoCAD' compatibility mode active (MacOSX 10.11.2, French locale):
![fidocadj_compatibility_mode_on](https://cloud.githubusercontent.com/assets/11355790/12688669/ee890ec6-c6d7-11e5-96fa-e9890d4bf255.png)
